import { Item } from "../interfaces";

/** Dummy user data. */
export const sampleUserData: Item[] = [
  { id: 101, name: "TAMALES DE POLLO O CERDO", type: "0ENTRADAS" },
  { id: 102, name: "PAPA A LA HUANCAÍNA", type: "0ENTRADAS" },
  { id: 103, name: "CAUSA DE ATÚN", type: "0ENTRADAS" },
  { id: 104, name: "CAUSA DE POLLO", type: "0ENTRADAS" },
  { id: 105, name: "CALDO DE GALLINA", type: "1SOPAS" },
  { id: 106, name: "CALDO DE MOTE", type: "1SOPAS" },
  { id: 107, name: "SOPA A LA MINUTA", type: "1SOPAS" },
  { id: 108, name: "AGUADITO", type: "1SOPAS" },
  { id: 109, name: "SOPA WANTAN (pollo/cerdo)", type: "1SOPAS" },
  { id: 110, name: "ARROZ CHAUFA CRIOLLO", type: "2PLATOS CRIOLLOS" },
  { id: 111, name: "TALLARÍN SALTEADO CRIOLLO", type: "2PLATOS CRIOLLOS" },
  { id: 112, name: "LOMO SALTEADO", type: "2PLATOS CRIOLLOS" },
  { id: 113, name: "LOMO SALTEADO A LO POBRE", type: "2PLATOS CRIOLLOS" },
  { id: 114, name: "ANTICUCHOS CON RACHI", type: "2PLATOS CRIOLLOS" },
  { id: 115, name: "SECO DE CARNE c/ frejoles", type: "2PLATOS CRIOLLOS" },
  { id: 116, name: "AJI DE GALLINA", type: "2PLATOS CRIOLLOS" },
  {
    id: 117,
    name: "ARROZ CON POLLO c/ papa a la huancaína",
    type: "2PLATOS CRIOLLOS",
  },
  { id: 118, name: "POLLADA", type: "2PLATOS CRIOLLOS" },
  { id: 119, name: "BISTECK A LO POBRE", type: "2PLATOS CRIOLLOS" },
  { id: 120, name: "CHICHARRON DE CERDO", type: "2PLATOS CRIOLLOS" },
  { id: 121, name: "WANTAN FRITO x12 un.", type: "3CHIFA" },
  { id: 122, name: "CHAUFA CHIFA", type: "3CHIFA" },
  { id: 123, name: "TALLARÍN CHIFA", type: "3CHIFA" },
  { id: 124, name: "AEROPUERTO CHIFA", type: "3CHIFA" },
  { id: 125, name: "COMBINADO CHIFA", type: "3CHIFA" },
  { id: 126, name: "ARROZ CHUFA VEGETARIANO", type: "4VEGETARIANOS" },
  { id: 127, name: "TALLARÍN SALTEADO VEGETARIANO", type: "4VEGETARIANOS" },
  { id: 128, name: "SALTEADO DE VERDURAS", type: "4VEGETARIANOS" },
  { id: 129, name: "POLLO CHIJAUKAY", type: "4VEGETARIANOS" },
  { id: 130, name: "CERDO AGRIDULCE", type: "4VEGETARIANOS" },
  { id: 131, name: "LECHE DE TIGRE", type: "5PESCADOS Y MARISCOS" },
  { id: 132, name: "RABAS", type: "5PESCADOS Y MARISCOS" },
  { id: 133, name: "CAUSA ACEVICHADA", type: "5PESCADOS Y MARISCOS" },
  { id: 134, name: "CEVICHE CLÁSICO (pescado)", type: "5PESCADOS Y MARISCOS" },
  { id: 135, name: "CEVICHE MIXTO", type: "5PESCADOS Y MARISCOS" },
  { id: 136, name: "ARROZ CHAUFA DE MARISCOS", type: "5PESCADOS Y MARISCOS" },
  {
    id: 137,
    name: "TALLARÍN SALTEADO DE MARISCOS",
    type: "5PESCADOS Y MARISCOS",
  },
  { id: 138, name: "ARROZ CON MARISCOS", type: "5PESCADOS Y MARISCOS" },
  { id: 139, name: "CHICHARRÓN DE PESCADO", type: "5PESCADOS Y MARISCOS" },
  { id: 140, name: "JALEA MIXTA", type: "5PESCADOS Y MARISCOS" },
  {
    id: 141,
    name: "PESCADO FRITO (mero entero)",
    type: "5PESCADOS Y MARISCOS",
  },
  { id: 142, name: "SUDADO DE PESCADO", type: "5PESCADOS Y MARISCOS" },
  { id: 143, name: "PARIHUELA", type: "5PESCADOS Y MARISCOS" },
  { id: 144, name: "ORGÍA DE MARISCOS", type: "5PESCADOS Y MARISCOS" },
  { id: 145, name: "MERO A LO MACHO", type: "5PESCADOS Y MARISCOS" },
  {
    id: 146,
    name: "TALLARINES A LA HUANCAÍNA CON LOMO SALTEADO",
    type: "6ESPECIALIDADES DEL CHEF",
  },
  {
    id: 147,
    name: "ALLARINES VERDES c/ BIFE y PAPA A LA HUANCAÍNA",
    type: "6ESPECIALIDADES DEL CHEF",
  },
  {
    id: 148,
    name: "TACU TACU CON LOMO SALTEADO",
    type: "6ESPECIALIDADES DEL CHEF",
  },
  {
    id: 149,
    name: "TACU TACU CON SALSA DE MARISCOS",
    type: "6ESPECIALIDADES DEL CHEF",
  },
  { id: 150, name: "TACU TACU A LO POBRE", type: "6ESPECIALIDADES DEL CHEF" },
  { id: 151, name: "MOSTRITO MARINO", type: "6ESPECIALIDADES DEL CHEF" },
  { id: 152, name: "CEVICHE SAZÓN", type: "6ESPECIALIDADES DEL CHEF" },
  { id: 153, name: "SALCHIPAPA clásico ó especial", type: "7PROMOCIONES" },
  { id: 154, name: "SALCHIBROSTER", type: "7PROMOCIONES" },
  { id: 155, name: "SALCHILOMO", type: "7PROMOCIONES" },
  { id: 156, name: "MOSTRITO BROSTER", type: "7PROMOCIONES" },
  { id: 157, name: "MOSTRITO CON LOMO", type: "7PROMOCIONES" },
  { id: 158, name: "MILANESA DE POLLO NAPOLITANA", type: "7PROMOCIONES" },
  { id: 159, name: "1/4 POLLO BROSTER", type: "7PROMOCIONES" },
  { id: 160, name: "1/2 POLLO BROSTER", type: "7PROMOCIONES" },
  { id: 161, name: "POLLO BROSTER FAMILIAR", type: "7PROMOCIONES" },
];
